name: github-ci-deep

on:
  schedule:
    - cron: "23 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  assurance:
    uses: gomaja/github-ci/.github/workflows/deep.yml@f5d26f58210ae8219d74ee3d91109ece1809801b
