name: github-ci-deep

on:
  schedule:
    - cron: "23 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  assurance:
    uses: gomaja/github-ci/.github/workflows/deep.yml@f10be1183b42364176a7d3f1ebfd789aad8aba30
