name: github-ci-deep

on:
  schedule:
    - cron: "23 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  assurance:
    uses: gomaja/github-ci/.github/workflows/deep.yml@0ac5daac1e651a550eb3f361ec526138295e4e0f
